// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArygMjXGZ1MNNkYhMy_2-c3bbLbxzdu9E',
    appId: '1:23923915642:web:f727147b4d4bfb8c6574c3',
    messagingSenderId: '23923915642',
    projectId: 'cw03-bee8b',
    authDomain: 'cw03-bee8b.firebaseapp.com',
    storageBucket: 'cw03-bee8b.firebasestorage.app',
    measurementId: 'G-4EDFHD1Y6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3h6SSDCX5i7zvn8Ek8vNk-mYuYgO785E',
    appId: '1:23923915642:android:7e50cdfb5671da7e6574c3',
    messagingSenderId: '23923915642',
    projectId: 'cw03-bee8b',
    storageBucket: 'cw03-bee8b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArygMjXGZ1MNNkYhMy_2-c3bbLbxzdu9E',
    appId: '1:23923915642:web:a12e9f701e7a94b76574c3',
    messagingSenderId: '23923915642',
    projectId: 'cw03-bee8b',
    authDomain: 'cw03-bee8b.firebaseapp.com',
    storageBucket: 'cw03-bee8b.firebasestorage.app',
    measurementId: 'G-CVFYB6V09Q',
  );
}
